# BSD 3-Clause License
#
# Copyright (c) 2025 - <YEARS>, Sun Yat-sen University.
# All rights reserved.
#
# Authors:
# Hanamy: rongerch@outlook.com
#
# Paper:
# Aerodynamic Prior-free Trajectory Generation and Tracking Control for a Tail-sitter UAV.

"""Regenerate the "ma" (B-spline fitted) model parameters.

Pipeline: bspline_aero_fit.py -> data/bspline_fit_results/*.npz ->
this script -> config/aero/ma.yaml (the C++ side loads that file).

Paths are anchored at AP_PNC_DIR (absolute), per the project path rules.
"""

import os
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml


class MaParamsError(Exception):
    """Raised when fit results are missing or malformed."""


@dataclass(frozen=True)
class MaParamsConfig:
    """Locations and constants for the ma parameter regeneration."""

    fit_results_dir: str = "infra/sim_infra/aerodynamics/data/bspline_fit_results"
    output_yaml: str = "infra/sim_infra/aerodynamics/config/aero/ma.yaml"
    # 0.5 * rho * S / 2 * 3 * CL_slope_ref * drag_ref (see the paper).
    scale_factor: float = (
        0.5 * 1.184 * 0.24 / 2.0 * 3 * 0.5483863461851688 * 1.177888074834827
    )


def _root() -> Path:
    value = os.environ.get("AP_PNC_DIR", "")
    if not value or not Path(value).is_absolute():
        raise MaParamsError("AP_PNC_DIR must be set to an absolute project root")
    return Path(value)


def _load_fit_results(root: Path) -> dict[str, np.ndarray]:
    fit_dir = root / "infra/sim_infra/aerodynamics/data/bspline_fit_results"
    arrays: dict[str, np.ndarray] = {}
    for axis in ("cx", "cz"):
        path = fit_dir / f"bspline_fit_{axis}.npz"
        if not path.is_file():
            raise MaParamsError(f"missing fit results file: {path}")
        with np.load(path) as data:
            for kind in ("coefs", "knots"):
                key = f"{axis}_{kind}"
                if key not in data.files:
                    raise MaParamsError(f"{path}: missing key '{key}'")
                arrays[key] = np.asarray(data[key], dtype=float).ravel()
    for key, values in arrays.items():
        if values.size == 0 or not np.isfinite(values).all():
            raise MaParamsError(f"{key}: empty or non-finite values")
    return arrays


def write_ma_yaml(root: Path, arrays: dict[str, np.ndarray],
                  scale_factor: float) -> Path:
    """Write config/aero/ma.yaml; returns the written path."""
    output = root / "infra/sim_infra/aerodynamics/config/aero/ma.yaml"
    output.parent.mkdir(parents=True, exist_ok=True)
    content = {
        "scale_factor": scale_factor,
        "cx_coefs": [float(v) for v in arrays["cx_coefs"]],
        "cx_knots": [float(v) for v in arrays["cx_knots"]],
        "cz_coefs": [float(v) for v in arrays["cz_coefs"]],
        "cz_knots": [float(v) for v in arrays["cz_knots"]],
    }
    header = (
        "# B-spline fitted model parameters (\"ma\").\n"
        "# Generated by ma_params_writer.py from data/bspline_fit_results.\n"
    )
    with output.open("w", encoding="utf-8") as stream:
        stream.write(header)
        yaml.safe_dump(content, stream, sort_keys=False, default_flow_style=False)
    return output


def main() -> None:
    try:
        config = MaParamsConfig()
        root = _root()
        arrays = _load_fit_results(root)
        output = write_ma_yaml(root, arrays, config.scale_factor)
        print(f"[ma-params-writer] wrote {output}")
    except MaParamsError as exc:
        print(f"Error: {exc}")
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
